// src/constants.ts

// export const test_build = true;
export const test_build = process.env.NODE_ENV === 'development';

export const all_years: string[] = Array.from({ length: 1962 - 1919 + 1 }, (_, i) => (1919 + i).toString());

export const languageCodes = {
	English: 'en',
	Русский: 'ru',
	Українська: 'ua',
	Romanian: 'ro',
	Arabic: 'ar',
	Chinese: 'zh',
	Czech: 'cs',
	Danish: 'da',
	Dutch: 'nl',
	Finnish: 'fi',
	French: 'fr',
	German: 'de',
	Greek: 'el',
	Hebrew: 'he',
	Hindi: 'hi',
	Hungarian: 'hu',
	Italian: 'it',
	Japanese: 'ja',
	Korean: 'ko',
	Norwegian: 'no',
	Polish: 'pl',
	Portuguese: 'pt',
	Slovak: 'sk',
	Spanish: 'es',
	Swedish: 'sv',
	Thai: 'th',
	Turkish: 'tr',
	Vietnamese: 'vi'
} as { [key: string]: string };

export const bookNamesYear: { [key: string]: { year: string; short: string } } = {
	'Millions Now Living Will Never Die': { year: '1920', short: 'millions-now-living-will-never-die' },
	'Talking With The Dead': { year: '1920', short: 'talking-with-the-dead' },
	'The Harp of God': { year: '1921', short: 'the-harp-of-god' },
	'A Desirable Government': { year: '1924', short: 'a-desirable-government' },
	'The Way To Paradise': { year: '1925', short: 'the-way-to-paradise' },
	'Comfort For The People': { year: '1925', short: 'comfort-for-the-people' },
	Deliverance: { year: '1926', short: 'deliverance' },
	Creation: { year: '1927', short: 'creation' },
	'Freedom For The People': { year: '1927', short: 'freedom-for-the-people' },
	Government: { year: '1928', short: 'government' },
	Reconciliation: { year: '1928', short: 'reconciliation' },
	Life: { year: '1929', short: 'life' },
	'Light (Part 1)': { year: '1930', short: 'light-part-1' },
	'Light (Part 2)': { year: '1930', short: 'light-part-2' },
	Prophecy: { year: '1930', short: 'prophecy' },
	'Vindication (Part 1)': { year: '1931', short: 'vindication-part-1' },
	Preservation: { year: '1932', short: 'preservation' },
	'Vindication (Part 2)': { year: '1932', short: 'vindication-part-2' },
	'Vindication (Part 3)': { year: '1932', short: 'vindication-part-3' },
	Preparation: { year: '1933', short: 'preparation' },
	Jehovah: { year: '1934', short: 'jehovah' },
	Riches: { year: '1936', short: 'riches' },
	Enemies: { year: '1937', short: 'enemies' },
	Salvation: { year: '1939', short: 'salvation' },
	Religion: { year: '1940', short: 'religion' },
	Children: { year: '1941', short: 'children' },
	'The New World': { year: '1942', short: 'the-new-world' },
	'The Truth Shall Make You Free': { year: '1943', short: 'the-truth-shall-make-you-free' },
	'The Kingdom is at Hand': { year: '1944', short: 'the-kingdom-is-at-hand' },
	'Let God Be True': { year: '1946', short: 'let-god-be-true' },
	'Equipped For Every Good Work': { year: '1946', short: 'equipped-for-every-good-work' },
	'What Has Religion Done for Mankind': { year: '1951', short: 'what-has-religion-done-for-mankind' },
	'Defending and Legally Establishing the Good News': {
		year: '1950',
		short: 'defending-and-legally-establishing-the-good-news'
	},
	'Make Sure Of All Things': { year: '1953', short: 'make-sure-of-all-things' },
	'Jehovahs Witnesses The New World Society': { year: '1955', short: 'jehovahs-witnesses-the-new-world-society' },
	'Qualified To Be Ministers': { year: '1955', short: 'qualified-to-be-ministers' },
	'What Do the Scriptures Say About Survival After Death': {
		year: '1955',
		short: 'what-do-the-scriptures-say-about-survival-after-death'
	},
	'You May Survive Armageddon into God\'s New World': {
		year: '1955',
		short: 'you-may-survive-armageddon-into-gods-new-world'
	},
	'Faith On The March': { year: '1957', short: 'faith-on-the-march' },
	'From Paradise Lost To Paradise Regained': { year: '1958', short: 'from-paradise-lost-to-paradise-regained' },
	'Your Will Be Done On Earth': { year: '1958', short: 'your-will-be-done-on-earth' }
};

export const bookAliases: { [key: string]: string } = {
	Gen: 'Genesis',
	Ex: 'Exodus',
	Lev: 'Leviticus',
	Num: 'Numbers',
	Deut: 'Deuteronomy',
	Josh: 'Joshua',
	Judg: 'Judges',
	Ruth: 'Ruth',
	'1 Sam': '1 Samuel',
	'2 Sam': '2 Samuel',
	'1 Ki': '1 Kings',
	'2 Ki': '2 Kings',
	'1 Chr': '1 Chronicles',
	'2 Chr': '2 Chronicles',
	Ezra: 'Ezra',
	Neh: 'Nehemiah',
	Esth: 'Esther',
	Job: 'Job',
	Ps: 'Psalm',
	Pss: 'Psalm',
	Prov: 'Proverbs',
	Eccl: 'Ecclesiastes',
	Song: 'Song of Solomon',
	Isa: 'Isaiah',
	Jer: 'Jeremiah',
	Lam: 'Lamentations',
	Ezek: 'Ezekiel',
	Dan: 'Daniel',
	Hos: 'Hosea',
	Joel: 'Joel',
	Amos: 'Amos',
	Obad: 'Obadiah',
	Jonah: 'Jonah',
	Mic: 'Micah',
	Nah: 'Nahum',
	Hab: 'Habakkuk',
	Zeph: 'Zephaniah',
	Hag: 'Haggai',
	Zech: 'Zechariah',
	Mal: 'Malachi',
	Matt: 'Matthew',
	Mark: 'Mark',
	Luke: 'Luke',
	John: 'John',
	Acts: 'Acts',
	Jas: 'James',
	'1 Pet': '1 Peter',
	'2 Pet': '2 Peter',
	'1 John': '1 John',
	'2 John': '2 John',
	'3 John': '3 John',
	Jude: 'Jude',
	Rom: 'Romans',
	'1 Cor': '1 Corinthians',
	'2 Cor': '2 Corinthians',
	Gal: 'Galatians',
	Eph: 'Ephesians',
	Phil: 'Philippians',
	Col: 'Colossians',
	'1 Thess': '1 Thessalonians',
	'2 Thess': '2 Thessalonians',
	'1 Tim': '1 Timothy',
	'2 Tim': '2 Timothy',
	Titus: 'Titus',
	Phlm: 'Philemon',
	Heb: 'Hebrews',
	Rev: 'Revelation'
};

export const booksMaxChapters: { [key: string]: number } = {
	Genesis: 50,
	Exodus: 40,
	Leviticus: 27,
	Numbers: 36,
	Deuteronomy: 34,
	Joshua: 24,
	Judges: 21,
	Ruth: 4,
	'1 Samuel': 31,
	'2 Samuel': 24,
	'1 Kings': 22,
	'2 Kings': 25,
	'1 Chronicles': 29,
	'2 Chronicles': 36,
	Ezra: 10,
	Nehemiah: 13,
	Esther: 10,
	Job: 42,
	Psalm: 150,
	Proverbs: 31,
	Ecclesiastes: 12,
	'Song of Solomon': 8,
	Isaiah: 66,
	Jeremiah: 52,
	Lamentations: 5,
	Ezekiel: 48,
	Daniel: 12,
	Hosea: 14,
	Joel: 3,
	Amos: 9,
	Obadiah: 1,
	Jonah: 4,
	Micah: 7,
	Nahum: 3,
	Habakkuk: 3,
	Zephaniah: 3,
	Haggai: 2,
	Zechariah: 14,
	Malachi: 4,
	Matthew: 28,
	Mark: 16,
	Luke: 24,
	John: 21,
	Acts: 28,
	Romans: 16,
	'1 Corinthians': 16,
	'2 Corinthians': 13,
	Galatians: 6,
	Ephesians: 6,
	Philippians: 4,
	Colossians: 4,
	'1 Thessalonians': 5,
	'2 Thessalonians': 3,
	'1 Timothy': 6,
	'2 Timothy': 4,
	Titus: 3,
	Philemon: 1,
	Hebrews: 13,
	James: 5,
	'1 Peter': 5,
	'2 Peter': 3,
	'1 John': 5,
	'2 John': 1,
	'3 John': 1,
	Jude: 1,
	Revelation: 22
};

// ""
export const allWTNames: { [key: string]: any } = {
	'1919': {
		'1': '___NO_DATA___',
		'2': '___NO_DATA___',
		'3': '___NO_DATA___',
		'4': '___NO_DATA___',
		'5': '___NO_DATA___',
		'6': '___NO_DATA___',
		'7': '___NO_DATA___',
		'8': '___NO_DATA___',
		'9': '___NO_DATA___',
		'10': '___NO_DATA___',
		'11': '___NO_DATA___',
		'12': '___NO_DATA___',
		'13': 'Test of Sonship',
		'14': 'Views From the Watch Tower',
		'15': 'Blessed are the Fearless (Part 1)',
		'16': 'Blessed are the Fearless (Part 2)',
		'17': 'Glorifying God',
		'18': 'Views From the Watch Tower',
		'19': 'Report of General Convention',
		'20': 'Views From the Watch Tower',
		'21': 'Green Leaves and Budding Hopes',
		'22': 'Ransom Implies Restitution',
		'23': 'Views From the Watch Tower',
		'24': 'Annual Report For 1919'
	},
	'1920': {
		'1': 'Strengthened For Victory',
		'2': 'Views From the Watch Tower',
		'3': 'Views From the Watch Tower',
		'4': 'Views From the Watch Tower',
		'5': 'Views From the Watch Tower',
		'6': 'The Uses of Adversity',
		'7': 'Let Us Dwell in Peace',
		'8': 'Views From the Watch Tower',
		'9': 'Ambassadors of Peace',
		'10': 'Views From the Watch Tower',
		'11': 'Views From the Watch Tower',
		'12': 'Ransom and Sin-offering',
		'13': 'Gospel of the Kingdom',
		'14': 'Walking With God',
		'15': 'Law Covenant Benefits',
		'16': 'Convention Tour',
		'17': 'The New Covenant',
		'18': 'The Tabernacle of David',
		'19': 'The Glory of Zion',
		'20': 'European Tour',
		'21': 'Views From the Watch Tower',
		'22': 'European Tour (Continued)',
		'23': 'European Tour (Continued)',
		'24': 'Annual Report For 1920'
	},
	'1921': {
		'1': 'Triumphant Zion',
		'2': 'Views From the Watch Tower',
		'3': 'The Beauty of Holiness',
		'4': 'Views From the Watch Tower',
		'5': 'Views From the Watch Tower',
		'6': '"This Is My Body"',
		'7': '"This Is My Body" (Concluded)',
		'8': 'Love Divine',
		'9': 'Views From the Watch Tower',
		'10': 'Our Reasonable Service',
		'11': 'Views From the Watch Tower',
		'12': 'Murmuring Against Jehovah',
		'13': 'Views From the Watch Tower',
		'14': 'Questions W Ith Answers',
		'15': 'Views From the Watch Tower',
		'16': 'The Olive, the Fig, and the Vine',
		'17': 'Views From the Watch Tower',
		'18': 'Christians in Convention',
		'19': 'Views From the Watch Tower',
		'20': 'Prove All Things',
		'21': 'Views From the Watch Tower',
		'22': 'Jehovah the Comforter',
		'23': 'Views From the Watch Tower',
		'24': 'Annual Report 1921'
	},
	'1922': {
		'1': 'Christ My Life',
		'2': 'Approved Workmen',
		'3': 'Views From the Watch Tower',
		'4': '"This Do Ye ... in Remembrance of Me"',
		'5': 'Who Is Wise?',
		'6': 'Applying the Heart Unto Wisdom',
		'7': 'My Vow Unto the Lord',
		'8': 'Views From the Watch Tower',
		'9': 'The Gentile Times',
		'10': 'Chronology',
		'11': 'Seventy Years\' Desolation (Part 1)',
		'12': 'Views From the Watch Tower',
		'13': '"I Vow to ... Be On the Alert to Resist" (Part 1)',
		'14': 'Views From the Watch Tower',
		'15': 'European Tour (Part 2)',
		'16': 'European Tour (Part 4)',
		'17': 'European Tour (Part 5)',
		'18': 'European Tour (Part 6)',
		'19': 'Views From the Watch Tower',
		'20': 'Baptism',
		'21': 'Cedar Point Convention',
		'22': 'Divinely-Given Chronological Parallelisms (Part 1)',
		'23': 'Provisions For His Own',
		'24': 'Annual Report For 1922'
	},
	'1923': {
		'1': 'Outlook For Nineteen-Twenty-Three',
		'2': 'Views From the Watch Tower',
		'3': 'Are You Using His Pound?',
		'4': 'Memorial Till His Kingdom',
		'5': 'Loyalty the Test',
		'6': 'Views From the Watch Tower',
		'7': '"Slack Not Thine Hands"',
		'8': 'The Principal Thing-Love (Part 1)',
		'9': 'The Principal Thing-Love (Part 2)',
		'10': 'Views From the Watch Tower',
		'11': 'Privileges and Duties of Elders',
		'12': '"The Way of the Lord"',
		'13': 'A Clear Vision of Chronology',
		'14': 'Views From the Watch Tower',
		'15': 'The Called of God',
		'16': 'Loyalty',
		'17': 'Method of Deceit',
		'18': 'The Beloved of God',
		'19': 'Virgins Fair',
		'20': 'The Parable of the Sheep and the Goats',
		'21': 'Conventions',
		'22': '"Kept For Jesus Christ"',
		'23': 'Views From the Watch Tower',
		'24': 'Annual Report Nineteen Twenty-Three'
	},
	'1924': {
		'1': 'The Outlook For 1924',
		'2': 'Multiplied Mercies of God',
		'3': 'Views From the Watch Tower',
		'4': 'The Destiny of the Goats',
		'5': 'A Ransom For All',
		'6': 'Precious Memories',
		'7': 'The Christian\'s Strength',
		'8': 'Kept in Peace',
		'9': 'An Ideal Government',
		'10': 'Contend For the Faith',
		'11': 'The International Convention At Columbus, Ohio',
		'12': 'The Gifts and Fruits of the Spirit',
		'13': 'European Conventions',
		'14': 'Our Present Duties',
		'15': 'The Holy Ones of God',
		'16': 'Faith and Works',
		'17': 'The International Convention',
		'18': 'Civilization Doomed',
		'19': 'The Temptation - Fall and Victory',
		'20': 'Satan, the Enemy - Is He Bound?',
		'21': 'Prohibition',
		'22': 'The Christian\'s Conflict',
		'23': 'Annual Report For 1924',
		'24': 'Rapture of the Angels'
	},
	'1925': {
		'1': 'Work For the Anointed',
		'2': 'Your Sanctification',
		'3': 'The Robe of Righteousness',
		'4': 'The Year of Jubilee',
		'5': 'Birth of the Nation',
		'6': 'His Memorial',
		'7': 'Philosophy of the Ransom',
		'8': 'God\'s Great Gift',
		'9': 'For the Elect\'s Sake',
		'10': 'Messengers of the Lord',
		'11': 'Light in the Darkness',
		'12': 'The Way to Life',
		'13': 'Order, Peace and Unity',
		'14': 'The Remnant',
		'15': 'The Work in Europe',
		'16': 'Protection and Deliverance',
		'17': 'Diligence and Fervency',
		'18': 'The King in Action',
		'19': 'The Love of the Creator For His Creatures',
		'20': 'Conventions',
		'21': 'A Call to Action',
		'22': 'The Holy Spirit Poured Out',
		'23': 'Annual Report For 1925',
		'24': 'Peace and Good Will'
	},
	'1926': {
		'1': 'Who Will Honor Jehovah?',
		'2': 'Learning to Pray',
		'3': 'Pray For Peace',
		'4': 'Obedience Leads to Life',
		'5': 'The King\'s Memorial',
		'6': 'Manifestation of His Goodness',
		'7': 'Hypocrisy and the "True"',
		'8': 'The Shining Light',
		'9': 'Character or Covenant - Which?',
		'10': 'Holiness Unto the Lord',
		'11': 'Sacrifice and Service',
		'12': 'Sacrifice and Obedience',
		'13': 'European Conventions',
		'14': 'London Convention',
		'15': 'The Temple of God',
		'16': 'The Servant and Service',
		'17': 'The Winepress',
		'18': 'The New World',
		'19': 'The Price of Peace',
		'20': 'The Stone of Zion',
		'21': 'A Stone of Stumbling',
		'22': 'Liberty of the Prisoners',
		'23': 'New York Convention',
		'24': 'Earth\'s Rightful Governor'
	},
	'1927': {
		'1': 'Jehovah and His Works',
		'2': 'The Great Multitude',
		'3': 'The Son and Servant',
		'4': 'Servant - Good and Evil',
		'5': 'The Elijah Work',
		'6': 'The Elisha Work',
		'7': 'The Feast of Deliverance',
		'8': 'The New Creation',
		'9': 'Ministry of the New Creation',
		'10': 'The Resurrection',
		'11': 'The First Resurrection',
		'12': 'Resurrection Body',
		'13': 'The Overcomers',
		'14': 'Visits From Jehovah',
		'15': 'Place of Security',
		'16': 'Why in Security',
		'17': 'Defence and Security',
		'18': 'Jehovah Alone Be Thy Fear',
		'19': 'A Service Convention',
		'20': 'Freedom For the Peoples',
		'21': 'Christians\' Mission On Earth',
		'22': 'The Passing of the Powers',
		'23': '"A People For a Purpose"',
		'24': 'One Reason For God\'s Vengeance'
	},
	'1928': {
		'1': 'Honor His Name',
		'2': 'A People For His Name',
		'3': 'Jehovah\'s Presence',
		'4': 'Presence of Christ',
		'5': 'Our Passover',
		'6': 'Jehovah\'s Covenants',
		'7': 'The Law Covenant',
		'8': 'The Covenant by Sacrifice',
		'9': 'The New Covenant',
		'10': 'The New Covenant',
		'11': 'His Name Exalted',
		'12': 'Sure Mercies of David',
		'13': 'A Witness to the People',
		'14': 'Fixed Periods of Time',
		'15': 'Prepared For the Remnant',
		'16': 'The Antichrist',
		'17': 'God\'s Lightnings',
		'18': 'The Convention',
		'19': 'Jehovah Favors His Remnant',
		'20': 'Philadelphia Period',
		'21': 'Laodicean Period',
		'22': 'The Altar in Egypt',
		'23': 'The Altar in Egypt (Part 2)',
		'24': 'Ruler Out of Bethlehem'
	},
	'1929': {
		'1': 'I Will Praise My God',
		'2': 'True and Faithful Witness',
		'3': 'Praise Jehovah!',
		'4': 'Judging His People',
		'5': 'The Invaluable Favor',
		'6': 'Gracious Invitation',
		'7': 'Mount Zion and the City',
		'8': 'God of Battle',
		'9': 'Delight Thyself in Jehovah',
		'10': 'Jehovah Supreme',
		'11': 'The Higher Powers',
		'12': 'The Higher Powers (Part 2)',
		'13': 'Job Greater Than Abraham (Part 1)',
		'14': 'Job Disputes With Satan\'s Agents (Part 2)',
		'15': 'Job Sees the Truth (Part 3)',
		'16': 'Vindication of His Name',
		'17': 'Ambassadors',
		'18': 'Satan\'s organization',
		'19': 'Assembling of His People',
		'20': 'Satan\'s organization (Part 2)',
		'21': 'The Day of His Preparation',
		'22': 'His Name',
		'23': 'Locating the Time',
		'24': 'The Days of Daniel'
	},
	'1930': {
		'1': 'Sing Unto Jehovah',
		'2': 'Jehovah\'s Royal House',
		'3': 'The Royal House of God (Part 2)',
		'4': 'Jehovah\'s Royal House (Part 3)',
		'5': 'Jehovah\'s Royal House (Part 4)',
		'6': 'Jehovah\'s Royal House (Part 5)',
		'7': 'The Son of Man',
		'8': 'God\'s Servant Preserved',
		'9': 'Peace and Evil',
		'10': 'Peace and Evil (Part 2)',
		'11': 'Angels in Zion (Part 1)',
		'12': 'Angels in Zion (Part 2)',
		'13': 'Kingdom Fruits',
		'14': 'Bearing Fruit',
		'15': 'A Great Image (Part 1)',
		'16': 'A Great Image (Part 2)',
		'17': 'Holy Spirit',
		'18': 'The Man of Sin',
		'19': 'Stand Firm',
		'20': 'A Wine Vineyard',
		'21': 'The Prize',
		'22': 'Opposing God',
		'23': 'Confidence of the Remnant',
		'24': 'His Campaign'
	},
	'1931': {
		'1': 'Preservation of the Unselfish',
		'2': 'Goodness to His Servant',
		'3': 'His Temple',
		'4': 'His Temple (Part 2)',
		'5': 'His Temple (Part 3)',
		'6': 'Love of the Elect',
		'7': 'His Favored People',
		'8': 'Refreshing His People',
		'9': 'Encouraging the Faithful',
		'10': 'Esther and Mordecai',
		'11': 'Esther and Mordecai (Part 2)',
		'12': 'Esther and Mordecai (Part 3)',
		'13': 'Esther and Mordecai (Part 4)',
		'14': 'Esther and Mordecai (Part 5)',
		'15': 'Esther and Mordecai (Part 6)',
		'16': 'Abominations in Christendom',
		'17': 'Man With the Writer\'s Inkhorn',
		'18': 'The Convention',
		'19': 'A New Name',
		'20': 'Remnant to the Front',
		'21': 'Taught of God',
		'22': 'Praise of Jehovah',
		'23': 'Delivering the Testimony',
		'24': 'The Decisive Test'
	},
	'1932': {
		'1': 'Know Jehovah',
		'2': 'Faint-Hearted or Faithful',
		'3': 'The Rock',
		'4': 'The Memorial',
		'5': 'Publishing Jehovah\'s Name (Part 1)',
		'6': 'Publishing Jehovah\'s Name (Part 2)',
		'7': 'Publishing Jehovah\'s Name (Part 3)',
		'8': 'Publishing Jehovah\'s Name (Part 4)',
		'9': 'Publishing Jehovah\'s Name (Part 5)',
		'10': 'Publishing Jehovah\'s Name (Part 6)',
		'11': 'Pharaoh and Satan',
		'12': 'Gog and Magog',
		'13': 'Jehovah\'s Executioner (Part 1)',
		'14': 'Jehovah\'s Executioner (Part 2)',
		'15': 'Jehovah\'s Executioner (Part 3)',
		'16': 'Jehovah\'s organization (Part 1)',
		'17': 'Jehovah\'s organization (Part 2)',
		'18': 'Jehovah\'s House Desired (Part 1)',
		'19': 'Jehovah\'s House Desired (Part 2)',
		'20': 'Jehovah\'s House Desired (Part 3)',
		'21': 'Jehovah\'s House Desired (Part 4)',
		'22': 'Jehovah\'s House Desired (Part 5)',
		'23': 'Jehovah\'s House Desired (Part 6)',
		'24': '"Fulness of Times"'
	},
	'1933': {
		'1': 'Everlasting Strength',
		'2': 'His Loving-Kindness',
		'3': 'Spiritually Minded',
		'4': 'Jehovah\'s Honor',
		'5': 'Tribulation',
		'6': '"The Feast of Jehovah"',
		'7': 'Testimony of Jehovah (Part 1)',
		'8': 'Testimony of Jehovah (Part 2)',
		'9': 'Who Is For Jehovah?',
		'10': 'Jehovah\'s Prophet',
		'11': 'His Covenant People',
		'12': 'His Sanctuary',
		'13': 'His Sanctuary (Part 2)',
		'14': 'His Sanctuary (Part 3)',
		'15': 'Inspection',
		'16': 'Consolation',
		'17': 'Judgment and Execution',
		'18': 'Obedience',
		'19': 'Melchizedek',
		'20': 'Shepherds and Staves',
		'21': '"Fear Them Not"',
		'22': 'Laborer\'s Wages',
		'23': 'Laborer\'s Wages (Part 2)',
		'24': 'Refuge'
	},
	'1934': {
		'1': 'Hope',
		'2': '"Satisfied With Thy Likeness"',
		'3': 'Hope of a Tree',
		'4': 'Tree of Hope',
		'5': 'His Name (Part 1)',
		'6': 'His Name (Part 2)',
		'7': 'His Covenants (Part 1)',
		'8': 'His Covenants (Part 2)',
		'9': 'His Covenants (Part 3)',
		'10': 'His Covenants (Part 4)',
		'11': 'His Covenants (Part 5)',
		'12': 'His Covenants (Part 6)',
		'13': 'His Covenants (Part 7)',
		'14': 'His Covenants (Part 8)',
		'15': 'His Kindness (Part 1)',
		'16': 'His Kindness (Part 2)',
		'17': 'Wicked Spirits (Part 1)',
		'18': 'Wicked Spirits (Part 2)',
		'19': 'The Crucible (Part 1)',
		'20': 'The Crucible (Part 2)',
		'21': 'Feast of Conspirators (Part 1)',
		'22': 'Feast of Conspirators (Part 2)',
		'23': 'Lions\' Mouths (Part 1)',
		'24': 'Lions\' Mouths (Part 2)'
	},
	'1935': {
		'1': 'Jehovah\'s Battle (Part 1)',
		'2': 'Jehovah\'s Battle (Part 2)',
		'3': 'Jehovah\'s Battle (Part 3)',
		'4': 'Jehovah\'s Battle (Part 4)',
		'5': 'Jehovah\'s Battle (Part 5)',
		'6': 'Prophecy of the Trees (Part 1)',
		'7': 'Prophecy of the Trees (Part 2)',
		'8': 'Knowledge of His Will',
		'9': 'Seeking Knowledge (Part 1)',
		'10': 'Seeking Knowledge (Part 2)',
		'11': 'Seeking Knowledge (Part 3)',
		'12': 'Joyful Songs (Part 4)',
		'13': 'Joyful Songs (Part 5)',
		'14': 'Understanding Prophecy',
		'15': 'The Great Multitude (Part 1)',
		'16': 'The Great Multitude (Part 2)',
		'17': 'Prisoners (Part 1)',
		'18': 'Prisoners (Part 2)',
		'19': 'Prisoners (Part 3)',
		'20': 'Virgins',
		'21': 'Vengeance Upon the Philistines (Samson, Part 1)',
		'22': 'Vengeance Upon the Philistines (Samson, Part 2)',
		'23': 'Sustaining His Servant (Samson, Part 3)',
		'24': 'Tempted (Samson, Part 4)'
	},
	'1936': {
		'1': 'Blind Servant (Samson, Part 5)',
		'2': 'Defeat of the Philistines',
		'3': 'Defeat of the Philistines (Part 2)',
		'4': 'Our Responsibility',
		'5': 'Loyalty and Faithfulness',
		'6': 'The Lord\'s Day (Part 1)',
		'7': 'The Lord\'s Day (Part 2)',
		'8': 'Feasts',
		'9': 'Armageddon Survivors',
		'10': 'The Scapegoat',
		'11': 'Priests and Levites',
		'12': 'Obadiah (Part 1)',
		'13': 'Obadiah (Part 2)',
		'14': 'Obadiah (Part 3)',
		'15': 'Obadiah (Part 4)',
		'16': 'Gathering the Multitude (Part 1)',
		'17': 'Gathering the Multitude (Part 2)',
		'18': 'Gathering the Multitude (Part 3)',
		'19': 'Gathering the Multitude (Part 4)',
		'20': 'Work',
		'21': 'Malachi (Part 1)',
		'22': 'Malachi (Part 2)',
		'23': 'Malachi (Part 3)',
		'24': 'Malachi (Part 4)'
	},
	'1937': {
		'1': 'Malachi (Part 5)',
		'2': 'Malachi (Part 6)',
		'3': 'Jehovah\'s Provisions (Part 1)',
		'4': 'Jehovah\'s Provisions (Part 2)',
		'5': 'Jehovah\'s Provisions (Part 3)',
		'6': 'Jehovah\'s Provisions (Part 4)',
		'7': '"Song of the Harlot" (Part 1)',
		'8': '"Song of the Harlot" (Part 2)',
		'9': '"Song of the Harlot" (Part 3)',
		'10': 'Understanding',
		'11': 'Adversaries',
		'12': 'Opposing God (Part 1)',
		'13': 'Opposing God (Part 2)',
		'14': 'Racketeers (Part 1)',
		'15': 'Racketeers (Part 2)',
		'16': 'Companions',
		'17': 'His "Work" and His "Act" (Part 1)',
		'18': 'His "Work" and His "Act" (Part 2)',
		'19': 'His "Work" and His "Act" (Part 3)',
		'20': 'His "Work" and His "Act" (Part 4)',
		'21': 'His "Work" and His "Act" (Part 5)',
		'22': 'His "Work" and His "Act" (Part 6)',
		'23': 'His "Work" and His "Act" (Part 7)',
		'24': 'The Kingdom Interests'
	},
	'1938': {
		'1': 'Jeremiah',
		'2': 'Jonah (Part 1)',
		'3': 'Jonah (Part 2)',
		'4': 'Jonah (Part 3)',
		'5': 'Memorial',
		'6': 'His Flock (Part 1)',
		'7': 'His Flock (Part 2)',
		'8': 'Children (Part 1)',
		'9': 'Children (Part 2)',
		'10': 'Unity in Action',
		'11': 'Organization (Part 1)',
		'12': 'Organization (Part 2)',
		'13': 'His War (Part 1)',
		'14': 'His War (Part 2)',
		'15': 'His War (Part 3)',
		'16': 'His War (Part 4)',
		'17': 'Lovers of Righteousness (Part 1)',
		'18': 'Lovers of Righteousness (Part 2)',
		'19': 'Lovers of Righteousness (Part 3)',
		'20': '"Fill the Earth" (Part 1)',
		'21': '"Fill the Earth" (Part 2)',
		'22': 'Righteous World',
		'23': 'Knowledge',
		'24': 'Salvation'
	},
	'1939': {
		'1': 'Deliverance Guaranteed',
		'2': '"Government and Peace"',
		'3': 'Drama of Vindication (Part 1)',
		'4': 'Drama of Vindication (Part 2)',
		'5': 'Drama of Vindication (Part 3)',
		'6': 'Drama of Vindication (Part 4)',
		'7': 'Drama of Vindication (Part 5)',
		'8': 'Drama of Vindication (Part 6)',
		'9': 'Drama of Vindication (Part 7)',
		'10': 'The Ransom (Part 1)',
		'11': 'The Ransom (Part 2)',
		'12': 'Doom of Religion (Part 1)',
		'13': 'Doom of Religion (Part 2)',
		'14': 'Doom of Religion (Part 3)',
		'15': 'Doom of Religion (Part 4)',
		'16': 'Doom of Religion (Part 5)',
		'17': 'Doom of Religion (Part 6)',
		'18': 'Doom of Religion (Part 7)',
		'19': 'Doom of Religion (Part 8)',
		'20': 'Doom of Religion (Part 9)',
		'21': 'Neutrality',
		'22': 'Snares',
		'23': 'The Theocracy',
		'24': 'Lazarus Comforted'
	},
	'1940': {
		'1': 'Rejoice in His Salvation',
		'2': 'Reproach of Men',
		'3': 'Power of the Demons (Part 1)',
		'4': 'Power of the Demons (Part 2)',
		'5': 'Power of the Demons (Part 3)',
		'6': 'Refuge',
		'7': 'Instruction (Part 1)',
		'8': 'Instruction (Part 2)',
		'9': 'Instruction (Part 3)',
		'10': 'Instruction (Part 4)',
		'11': 'Instruction (Part 5)',
		'12': 'Instruction (Part 6)',
		'13': 'Instruction (Part 7)',
		'14': 'Instruction (Part 8)',
		'15': '"Times and Seasons" (Part 1)',
		'16': '"Times and Seasons" (Part 2)',
		'17': '"Times and Seasons" (Part 3)',
		'18': 'Ehud (Part 1)',
		'19': 'Ehud (Part 2)',
		'20': 'Ehud (Part 3)',
		'21': 'Salvation',
		'22': 'Drama of Vengeance (Part 1)',
		'23': 'Drama of Vengeance (Part 2)',
		'24': 'Persecution'
	},
	'1941': {
		'1': 'Drama of Vengeance (Part 3)',
		'2': 'Drama of Vengeance (Part 4)',
		'3': 'Drama of Vengeance (Part 5)',
		'4': 'Obedience',
		'5': 'Victory Song (Part 1)',
		'6': 'Victory Song (Part 2)',
		'7': 'Victory Song (Part 3)',
		'8': 'Victory Song (Part 4)',
		'9': 'Victory Song (Part 5)',
		'10': 'Noah\'s Day',
		'11': 'Man\'s True Guide',
		'12': 'Covenant Obligations',
		'13': 'Those That Forget God',
		'14': 'The Wise',
		'15': 'When the Righteous Rule',
		'16': 'Integrity',
		'17': 'Children of the King',
		'18': 'Demon Rule Ending (Part 1)',
		'19': 'Demon Rule Ending (Part 2)',
		'20': 'Demon Rule Ending (Part 3)',
		'21': 'Demon Rule Ending (Part 4)',
		'22': 'Demon Rule Ending (Part 5)',
		'23': 'Demon Rule Ending (Part 6)',
		'24': 'Demon Rule Ending (Part 7)'
	},
	'1942': {
		'1': 'Micah (Part 1)',
		'2': 'Micah (Part 2)',
		'3': 'Final Gathering',
		'4': 'Micah (Part 3)',
		'5': 'Micah (Part 4)',
		'6': 'Micah (Part 5)',
		'7': 'Micah (Part 6)',
		'8': 'Micah (Part 7)',
		'9': 'Micah (Part 8)',
		'10': 'Micah (Part 9)',
		'11': 'Micah (Part 10)',
		'12': 'Micah (Part 11)',
		'13': 'Song-Call to Action',
		'14': 'Defeat of Persecution',
		'15': 'Atonement For the New World (Part 1)',
		'16': 'Atonement For the New World (Part 2)',
		'17': 'Atonement For the New World (Part 3)',
		'18': 'Assembly Unto the Kingdom',
		'19': 'The Only Light',
		'20': 'Fighter For the New World (Part 1)',
		'21': 'Fighter For the New World (Part 2)',
		'22': 'Fighter For the New World (Part 3)',
		'23': 'Fighter For the New World (Part 4)',
		'24': 'Fighter For the New World (Part 5)'
	},
	'1943': {
		'1': 'Fighter For the New World (Part 6)',
		'2': '"More Than Conquerors"',
		'3': 'Faith of the Nation Tried',
		'4': 'Endurance Amid World Crisis',
		'5': 'In Remembrance of the King',
		'6': 'The King\'s Counsel At Memorial',
		'7': 'Desire For Life in the New World',
		'8': 'Suffering Precedes First Resurrection',
		'9': 'Living For the New World',
		'10': 'Safety At the Climax of Judgment',
		'11': 'Theocratic order Under Persecution',
		'12': 'New World Ambassadors to the Homes',
		'13': 'Supreme Court Interprets',
		'14': 'Kingdom Sign of the Servants',
		'15': 'Victory by Faith',
		'16': 'Assembly For Peace and Prosperity',
		'17': 'God of the Free',
		'18': 'Free Education For "Men of Good-Will"',
		'19': 'The Free Nation Keeping Truth',
		'20': 'A Feast Unto All Peoples',
		'21': 'The Prodigal Son in Need',
		'22': 'The Prodigal Son\'s Home-Coming',
		'23': 'Prayer and the New World',
		'24': 'Prayer For New World Government'
	},
	'1944': {
		'1': 'Divine Education of the Servant',
		'2': 'God\'s Freewoman',
		'3': 'The Seed of God\'s “Freewoman“',
		'4': 'The Firstborn Smitten',
		'5': 'World Regeneration',
		'6': 'The Firstfruits of Resurrection',
		'7': 'Destroying Man\'s Last Enemy',
		'8': 'Power of the Resurrection Hope',
		'9': 'The Glorious Treasure of Service',
		'10': 'Unity For the New World ',
		'11': '"The Foolishness of Preaching"',
		'12': '"The Father of Spirits"',
		'13': '"Bringing Many Sons Unto Glory"',
		'14': 'The "Called, and Chosen, and Faithful"',
		'15': 'The Anointed and "Men of Good-Will"',
		'16': 'Spirit in the Time of the End',
		'17': '"This Gospel Shall Be Preached"',
		'18': '"Seek Ye First the Kingdom"',
		'19': 'The King\'s Marriage Feast',
		'20': 'Organized For Final Work',
		'21': 'Theocratic organization in Action',
		'22': 'The Stranger and His Right',
		'23': 'The Stranger\'s Right Maintained',
		'24': '"Go, Disciple All the Nations"'
	},
	'1945': {
		'1': 'Commission of the Anointed',
		'2': 'Raising Up the Reconstructors',
		'3': 'Baptism - Why?',
		'4': 'The Kingdom Sabbath and Its Lord',
		'5': 'The King\'s Purge Against Religion',
		'6': 'The King\'s Feast of Liberation',
		'7': 'Provoking the Showdown',
		'8': 'A Remnant For the Kingdom',
		'9': 'After the "Fulness of the Gentiles", What?',
		'10': '"Your Reasonable Service"',
		'11': 'A People For the Issue',
		'12': 'Sure Foundation For the New World',
		'13': 'Immovable For the Right Worship',
		'14': '"Justification of Life"',
		'15': 'The Justifier and His Ways ',
		'16': 'Life-Giving Acquittal During This World',
		'17': 'Vindication of Jehovah\'s Servant',
		'18': 'Defense Through Knowledge',
		'19': 'The "New Song"',
		'20': '"Jehovah Hath Become King!"',
		'21': 'Living Under Grace, and Not the Law ',
		'22': 'Remembering the New World\'s Creator',
		'23': '"His Unspeakable Gift"',
		'24': '"Be Glad, Ye Nations, With His People"'
	},
	'1946': {
		'1': 'Strong Hearted For the Postwar Era',
		'2': 'The Joy of Liberation',
		'3': 'The Publisher of Peace and Salvation',
		'4': 'Consecration',
		'5': 'Preliminary to the Feast',
		'6': 'Sanctification',
		'7': 'Perfection',
		'8': '"Changed" to See God',
		'9': 'Rule of the Nations With a Rod of Iron',
		'10': 'The Great Shepherd and His Little Flock',
		'11': 'Ordaining the New World\'s Priesthood',
		'12': 'Installing the Everlasting Priesthood',
		'13': 'Vindicated On the Covenant by Sacrifice',
		'14': 'Return From the Land of the Enemy',
		'15': 'A New Covenant With a New Nation',
		'16': 'The Harvest, the End of the World',
		'17': 'Pure and Undefiled Worship',
		'18': 'Children in the "Time of the End"',
		'19': 'Glad Nations Theocratic Assembly of Jehovah\'s Witnesses',
		'20': 'Warning',
		'21': '"Let God Prove to Be True"',
		'22': 'Whose Witnesses?',
		'23': '"Seventy Weeks"',
		'24': 'The Life-Giving Call to the Nations'
	},
	'1947': {
		'1': 'Unity and Peace',
		'2': 'Marriage',
		'3': 'Singleness or Marriage in the Postwar World, Which?',
		'4': 'A Memorial of Integrity For God\'s Kingdom',
		'5': 'Libel and Sedition Against God',
		'6': 'Reasons For the Resurrection Hope',
		'7': 'Resurrection to a New World',
		'8': 'Divine Mercy and Forgiveness',
		'9': 'The Tongue: Its Wrong and Right Uses',
		'10': 'Inspiration',
		'11': 'Church and Kingdom',
		'12': 'Judgment Day For Jehovah\'s Vindication',
		'13': 'Judgment of Church and World',
		'14': 'Endurance That Wins',
		'15': '"Blessed Are the Eyes Which See"',
		'16': 'Praise That Guarantees Salvation',
		'17': 'Pushing the Advance of True Worship',
		'18': 'Turning in the Report',
		'19': 'The One King For All the Earth',
		'20': 'God\'s Ministers of Good News',
		'21': 'Love of Man to Man',
		'22': 'Profitable Tolerance',
		'23': 'The Theocratic organization and Its Governing Body',
		'24': 'The Spreading of Song Among All Nations'
	},
	'1948': {
		'1': 'Why They Are So Different in 1948',
		'2': 'The Signal to the Peoples',
		'3': 'Memorial of Founding the New World',
		'4': 'Gaining Entrance to Permanent Dwellings',
		'5': '“The Trinity“ Opposed to God\'s Kingdom',
		'6': '"That the Ministry Be Not Blamed"',
		'7': 'Are You Saved?',
		'8': '"The God of Hope"',
		'9': 'Hearing Ears',
		'10': 'Ignorance of Sin',
		'11': 'Testing the Spirits in the World Crisis',
		'12': 'Advance to Maturity or Relapse Into Sin, Which?',
		'13': 'Transmitting the Sacred Record',
		'14': '"Our Common Salvation"',
		'15': 'Paying Respect to the Judge',
		'16': 'The Way of Pleasantness and Prosperity',
		'17': 'A Healthful Means of Gain',
		'18': 'Gifts According to Measure',
		'19': 'King For a Thousand Years',
		'20': 'Ministers At the World\'s End',
		'21': 'The Marriage in Heaven',
		'22': 'The Giver of Immortality',
		'23': 'Not a Slow God',
		'24': 'Praise to the Nations Yet More and More'
	},
	'1949': {
		'1': 'Ministers to Uphold the Issue in 1949',
		'2': 'Earth\'s Destiny After This World\'s End',
		'3': 'Bible Study, a Roy Al Requirement',
		'4': 'The Comfort For the Displaced People',
		'5': 'The New Covenant Attaining Final Success',
		'6': 'The Willing Burdens of the Free and Strong',
		'7': 'The Hope of Nations',
		'8': 'Restoration to Life by Resurrection',
		'9': 'Woman',
		'10': 'Sheep, Goats, and the King\'s Brothers',
		'11': 'Endless Life Through Mercy',
		'12': 'Paradise',
		'13': 'Messiah\'s Presence',
		'14': 'The Sign That Messiah Is Present',
		'15': 'The Manifestation of Messiah\'s Presence',
		'16': 'Israel',
		'17': '"Hell" Used As a Scare',
		'18': 'Kingdom Covenant Provides New World\'s Ruler',
		'19': 'It Is Nearer Than They Think',
		'20': 'The Taunt-Song Against Satan the Devil',
		'21': 'The World\'s “Time of the End“',
		'22': 'The More Excellent Way of Love ',
		'23': 'Love\'s Expression',
		'24': '"Preach the Word"'
	},
	'1950': {
		'1': 'Be Rich in Good Works',
		'2': 'A God of Warning',
		'3': 'What Do You Do With Your Time?',
		'4': '"Stick to Your Work"',
		'5': 'A Call to Praise',
		'6': 'Fearless At the World\'s End',
		'7': 'Divine Education Bears Good Fruit',
		'8': 'Servants Feed the Flock',
		'9': '"Whatever Else You Get, Get Understanding"',
		'10': 'Living U P to the Name',
		'11': 'A Mind Freed For Godly Combat',
		'12': 'A Victory Dedicated to Jehovah\'s Honor',
		'13': 'Feasts to Jehovah',
		'14': 'Equipping the New World organization',
		'15': 'Serving W Ith the Servant',
		'16': '"The Increase of His Government"',
		'17': 'Taking in Life-Giving Knowledge',
		'18': 'Turning to the Peoples a Pure Language',
		'19': '"The Wisdom From Above"',
		'20': 'Clergy Voice Unwarranted Criticism',
		'21': 'Doing the Work Assigned',
		'22': 'Paying Back God\'s Things to God',
		'23': 'Does Papal Encyclical \'Resist Compromise?',
		'24': 'Jehovah\'s Witnesses Again Endure Totalitarian Hate'
	},
	'1951': {
		'1': 'God Knows and Protects His Own',
		'2': 'Why Mourning Excels Mirth',
		'3': 'Why Jehovah\'s Witnesses Are Not Pacifists',
		'4': 'World Hypocrisy, Christian Zeal',
		'5': 'Prayers For Peace',
		'6': 'Time Better Than Money',
		'7': 'Preaching in the Island',
		'8': 'In Defense of Marriage',
		'9': 'Religious Meeting in Public Park No Union of Church and State',
		'10': 'Receiving Mercy by Showing Mercy',
		'11': 'The Moral Collapse',
		'12': 'Conquer Your Fears!',
		'13': 'Quebec\'s Campaign of Persecution Suffers Another Stunning Blow',
		'14': 'Jehovah\'s Word Endures Forever!',
		'15': '"Proclaim Liberty Throughout All the Land"',
		'16': 'When Christianity Went Underground',
		'17': 'Cheap Talk Versus True Principles',
		'18': 'The Biggest Optimists',
		'19': 'What to Love and What to Hate',
		'20': 'Education That Brings Success',
		'21': 'Charity in Christendom',
		'22': 'Baptism For Salvation and Fire Baptism',
		'23': 'International "Clean Worship" Assembly in London',
		'24': 'Mankind\'s Greatest Leader'
	},
	'1952': {
		'1': 'Happiness in An Unstable World',
		'2': 'Papal Unity Versus Communism',
		'3': 'Avoid Shame by Study',
		'4': '"Hold a Good Conscience"',
		'5': 'Keeping the organization Clean',
		'6': 'Are You Choosing Life or Death?',
		'7': 'Is God Responsible For World Distress?',
		'8': 'Waterless Clouds, Fruitless Trees',
		'9': 'Healing For Life in the New World',
		'10': 'Missionary Work Spreads Liberty and Love',
		'11': 'Ministers of Good News At Your Door',
		'12': 'The Marriage Ceremony',
		'13': 'Subtly Discrediting God\'s Word',
		'14': '"Feed My Young Lambs"',
		'15': '"Defending and Legally Establishing the Good News"',
		'16': 'The Defense That Wins',
		'17': 'Clergy Philosophers Void the Bible',
		'18': '"The Things Unseen Are Everlasting"',
		'19': 'The Need to Awake',
		'20': '"The Word of God Is Alive"',
		'21': 'Efforts to Undermine the Bible',
		'22': '"All the Gods of the Nations Are Idols"',
		'23': 'Recommending Themselves As God\'s Ministers',
		'24': 'The Unchristian Christmas'
	},
	'1953': {
		'1': 'Happiness in Giving',
		'2': 'The Mental Breakdown',
		'3': 'Priestly Advocate of Error Discomfited',
		'4': '"How Do You Make a Convert?"',
		'5': 'The World\'s Integrity On the Wane',
		'6': 'Does Sin Mean Progress?',
		'7': '"They Say But Do Not Perform"',
		'8': 'Why Professed Christians Lack Zeal',
		'9': 'Why Maturity Is Lacking',
		'10': 'Youth No Bar to the Ministry',
		'11': 'Predestination and Jehovah\'s Foreknowledge',
		'12': 'Religious Pretext For Vain Show',
		'13': 'A Peace Measure?',
		'14': 'Political Expediency or Principle?',
		'15': 'The Bible and Medical Science',
		'16': 'Is Compromise Excusable?',
		'17': 'Why Seminaries Weaken Faith',
		'18': 'Jehovah, Not a Primitive Concept',
		'19': 'Awakening the Sleepers',
		'20': 'Generosity Enriches',
		'21': 'Supernatural Religion a Superstition?',
		'22': 'Modern Knowledge Vindicates the Bible',
		'23': 'Clerical Wishful Thinking',
		'24': 'Selfish Christmas'
	},
	'1954': {
		'1': 'Contending According to the Rules?',
		'2': 'The Folly of Apathy',
		'3': 'More Missing Than Links',
		'4': 'Spiritual Apathy Torments Clergy',
		'5': 'Aid to Understanding',
		'6': 'The Sensible View of Money',
		'7': 'Are You Holding Fast Your Confidence?',
		'8': 'Where Is "This Faith" Found?',
		'9': 'Foxhole Faith Is Not True Faith',
		'10': 'Choosing Your Own Food',
		'11': 'Man Created With Urge to Worship',
		'12': 'Can Christians Change the World?',
		'13': 'Watering Down Christianity',
		'14': 'Watch Your Strength!',
		'15': 'Man\'s Best Hope For Peace',
		'16': 'Meaning of the World\'s Woes',
		'17': 'Understanding God\'s Word Means Life',
		'18': 'Looking Forward to Real Living',
		'19': 'The Hope of a New Earth',
		'20': 'A Message of Encouragement and Value',
		'21': 'Why Fear the Future?',
		'22': 'World Peace - by Whom?',
		'23': 'Hope For the Living and the Dead',
		'24': 'What Is This Christmas Spirit?'
	},
	'1955': {
		'1': 'Bracing Up the Mind For New Nation Activity',
		'2': 'True Christians Defeat Persecution',
		'3': 'Choosing Life Now to Keep Alive Forever',
		'4': 'Wanted: Robot Minds For Today',
		'5': 'Exclaiming About the Peril of Our Time',
		'6': 'What Is Applied Christianity?',
		'7': 'Pray For World Peace',
		'8': 'The Cultural Breakdown',
		'9': 'Will You Reason On Religion',
		'10': 'Neighbor Love Not Enough',
		'11': 'The Foggy Hope',
		'12': 'Italian Communists and the Catholic Church',
		'13': 'Christ\'s Coming An Academic Question?',
		'14': 'Should the Bible Be Your Guide?',
		'15': 'Priest Advises Einstein',
		'16': 'Keep Up With the Good Examples',
		'17': 'Optimistic in the Face of Disaster',
		'18': 'Secular Progress and Spiritual Sloth',
		'19': 'The Use of Images in Christian Worship',
		'20': 'Business Teaches Churches Morality?',
		'21': '"A Wider Interpretation of the Christian Faith"?',
		'22': 'Does the Bible Teach Universal Salvation?',
		'23': 'Actively Trusting Jehovah Free From Fear',
		'24': '\'Sorry, I Have No Time!\''
	},
	'1956': {
		'1': 'Why Bother About Religion?',
		'2': 'Religion in Form Only',
		'3': 'Conscious of Your Spiritual Need?',
		'4': 'Do You Believe Only What You Can See?',
		'5': 'Bridle Your Tongue',
		'6': 'Peace of Mind Through Accurate Knowledge',
		'7': 'Making All Mankind One Under Their Creator',
		'8': 'Why Examine the Bible?',
		'9': 'The Clergy and the Book ',
		'10': 'Why Are the Clergy Discouraged?',
		'11': 'Is Sincerity Enough?',
		'12': 'The Book of Books',
		'13': '"Rise Up to the Opportunities"',
		'14': 'Stop Evil, Start Good',
		'15': 'Dusty Bible No Laughing Matter',
		'16': 'Communists Continue to Persecute Jehovah\'s Witnesses',
		'17': '"He Made Out of One Man Every Nation"',
		'18': 'Learn How to Learn',
		'19': 'Flags and Religion',
		'20': 'Is God a Segregationist?',
		'21': 'The Need For Solitude',
		'22': 'Does the Bible Agree With Your Church?',
		'23': 'Freedom Suppressed in Solomon Islands',
		'24': 'Do You Fear Men or God?'
	},
	'1957': {
		'1': 'Which Part Do You Read?',
		'2': 'Does the End Justify the Means?',
		'3': 'What Will You Give For Your Life?',
		'4': 'Why Should a Religion Come to Your Door?',
		'5': 'Do You Walk With God?',
		'6': 'Is Optimism Dead?',
		'7': 'What Is Easter All About?',
		'8': '"Go in Through the Narrow Gate"',
		'9': 'Do Not Disturb!',
		'10': 'Clergymen: Commanders-In-Chief or Tolerated Chaplains?',
		'11': 'Conspiracy Against Jehovah\'s Name?',
		'12': 'Jehovah\'s Name a Strong Tower',
		'13': 'House-To-House Preaching Most Effective',
		'14': 'A Message From Invisible Space',
		'15': 'Protestantism\'s Twin Plight',
		'16': 'Religious Persecution in Paraguay',
		'17': 'Religion - Has It the Key to Unity?',
		'18': 'Is Your Conscience a Sure Guide?',
		'19': 'Beware of Gifts!',
		'20': 'The Folly of War',
		'21': 'Can You Wait?',
		'22': 'The Pitfall of Modern Youth',
		'23': 'Glory From the Weak',
		'24': 'Is Christmas Giving Christian?'
	},
	'1958': {
		'1': 'A Fading Flower Ceases to Fade',
		'2': 'Walk With Care',
		'3': 'Did They Decide With Understanding?',
		'4': 'God Not Discouraged',
		'5': 'A World Without Locks',
		'6': 'A King Shall Reign in Righteousness',
		'7': 'Don\'tJudge by the Face',
		'8': 'A New Song For All Men of Good Will',
		'9': 'Who Will Strike the Deciding Blow?',
		'10': 'Why Youth Is Uncommitted',
		'11': 'When Will This Madness Cease?',
		'12': 'It Is Sinking In!',
		'13': 'Give Credit Where Credit Is Due',
		'14': 'Let Your Way Be Guided',
		'15': 'Learn From the Past',
		'16': 'Is It Safe to Be Different?',
		'17': 'Not Letting Your Left Hand Know',
		'18': 'Never Too Old to Learn',
		'19': 'How Practical Is Your Knowledge?',
		'20': 'But Where Are the Fruits?',
		'21': 'Why Be Impatient?',
		'22': '"Give Us More Faith"',
		'23': 'The Wiser Refugees',
		'24': 'Thinking About Christmas?'
	},
	'1959': {
		'1': 'Are You Spiritually Alive?',
		'2': 'Do You Have Time?',
		'3': 'Cheapest and Yet Costliest',
		'4': 'What Basis For Hope?',
		'5': 'What Do You Live For? ',
		'6': 'Can You Resist Temptation?',
		'7': 'How to Prove You Have Christian Faith',
		'8': 'The Age of Violence',
		'9': 'Is God to Blame?',
		'10': '"Feed My Little Sheep"',
		'11': 'Intolerance Is a Sign of Weakness',
		'12': '"Brace Up Your Minds For Activity"',
		'13': 'Walk in the Light From God',
		'14': 'Life Is Valuable',
		'15': 'Generosity Is Proof of Wisdom',
		'16': 'Are You Being Kind to Yourself?',
		'17': 'Why Do the Wicked Prosper?',
		'18': 'It Is Good to Be Gracious',
		'19': 'Misplaced Confidence',
		'20': 'God\'s Ways or Man\'S?',
		'21': 'The Bible Still Without Peer',
		'22': 'Are God\'s Interests Served by Gambling?',
		'23': 'Why Give Thanks?',
		'24': 'God Will Do It His Way'
	},
	'1960': {
		'1': 'Prayers For God\'s Kingdom Not in Vain',
		'2': '\'Neither Will Pain Be Any More\'',
		'3': '"Death Will Be No More"',
		'4': 'A Society Without Crime',
		'5': 'Government by God',
		'6': 'Life in a Righteous New World',
		'7': 'When Will Oppression End?',
		'8': 'Praying to Be Heard',
		'9': 'Why Murmur?',
		'10': 'In What Do You Boast?',
		'11': 'Is Our Civilization Facing a Fall?',
		'12': '"Sharper Than Any Two-Edged Sword"',
		'13': 'Wisdom Hates Pride',
		'14': 'The Truth Shall Stand',
		'15': 'Do You Turn the Other Cheek?',
		'16': 'Who Can Say He Is Without Sin?',
		'17': 'The Age of Rebellion',
		'18': 'Is It Right to Hate Wrong?',
		'19': 'Numbers Are Not Enough',
		'20': 'Gratitude For Little Things',
		'21': '"Rice Christians" Are No Christians',
		'22': 'Does It Hurt You to Give?',
		'23': '"Pay Attention to How You Listen"',
		'24': 'Sow Bountifully and Reap Bountifully'
	},
	'1961': {
		'1': 'Who Is Your God?',
		'2': 'What Do You Know About God\'s Son?',
		'3': 'Why Do You Believe the Bible?',
		'4': 'Is Heaven Your Destiny?',
		'5': 'What Is the Destiny of the Wicked?',
		'6': 'Is All Religion Good?',
		'7': 'Do You Serve God or Expect God to Serve You?',
		'8': 'Appreciating Life and the Life-Giver',
		'9': 'Hope Safeguards the Mind',
		'10': 'Do You Tread On Others\' Toes Needlessly?',
		'11': 'Do You Teach Your Children the Counsel of God?',
		'12': 'Is Apology a Sign of Weakness?',
		'13': 'Neighbor Love No Substitute For Love of God',
		'14': 'A Time and Place For Everything',
		'15': 'Do Your Ears Hear With Annoyance?',
		'16': 'Does Sympathetic Understanding Mark Your Giving?',
		'17': 'Do You Ignore Your Blessings?',
		'18': 'Do You Keep Your Word?',
		'19': 'When God Speaks, Do You Listen?',
		'20': 'Why Must You Know Your Bible?',
		'21': 'Man Learns From God\'s Creations',
		'22': 'Fear or Affection - Which Do You Instill?',
		'23': 'Are You Considerate of Others?',
		'24': 'Why Read the Bible?'
	},
	'1962': {
		'1': 'Divine Promises of a New World',
		'2': 'Why a New World Is Assured',
		'3': 'Foundation For a Righteous New World',
		'4': 'Are You Conscious of Your Spiritual Need?',
		'5': 'God\'s New World in Our Generation',
		'6': 'How the New World Comes In',
		'7': 'Life in a Paradise New World',
		'8': 'Love of the Truth',
		'9': 'Living Now For God\'s New World',
		'10': 'Who Can Be Trusted?',
		'11': 'Pay Attention to Wisdom',
		'12': 'Do You Avoid Enemies of Happiness?',
		'13': 'The Faith of Abraham',
		'14': 'Have the Endurance of Job Today',
		'15': 'The Wisdom of Solomon',
		'16': 'Be Strong, Like Samson!',
		'17': 'Be Submissive As Was Sarah',
		'18': 'Courage Like David\'s For Modern Times',
		'19': 'Happy the Merciful',
		'20': 'Why a Fearful World',
		'21': 'Spare Your Words',
		'22': 'Why Take a Negative Viewpoint?',
		'23': 'Using Power in the Fear of Jehovah',
		'24': 'Humility-Love\'s Complement'
	}
};
